export const titles: string[] = [
	'A Clockwork Orange',
	'All Quiet on the Western Front',
	'Amadeus',
	'American Graffiti',
	'An American in Paris',
	'Annie Hall',
	'A Place in the Sun',
	'Apocalypse Now',
	'A Streetcar Named Desire',
	'Bonnie and Clyde',
	'Braveheart',
	'Butch Cassidy and the Sundance Kid',
	'Casablanca',
	'Chinatown',
	'Citizen Kane',
	'City Lights',
	'Close Encounters of the Third Kind',
	'Dances with Wolves',
	'Doctor Zhivago',
	'Double Indemnity',
	'Dr Strangelove',
	'Forrest Gump',
	'From Here to Eternity',
	'Gladiator',
	'Gone with the Wind',
	'Goodfellas',
	'Good Will Hunting',
	'High Noon',
	'It Happened One Night',
	'Jurassic Park',
	'Lawrence of Arabia',
	'Midnight Cowboy',
	'Mutiny on the Bounty',
	'My Fair Lady',
	'Nashville',
	'Network',
	'North by Northwest',
	'On the Waterfront',
	'Platoon',
	'Pulp Fiction',
	'Raging Bull',
	'Raiders of the Lost Ark',
	'Rain Man',
	'Rear Window',
	'Rebel Without a Cause',
	'Saving Private Ryan',
	'Some Like It Hot',
	'Stagecoach',
	'Sunset Blvd',
	'Taxi Driver',
	'Terms of Endearment',
	'The African Queen',
	'The Apartment',
	'The Best Years of Our Lives',
	'The Bridge on the River Kwai',
	'The Deer Hunter',
	'The Exorcist',
	'The French Connection',
	'The Godfather',
	'The Graduate',
	'The Grapes of Wrath',
	'The Great Dictator',
	'The Green Mile',
	'The Maltese Falcon',
	'The Philadelphia Story',
	'The Pianist',
	'The Searchers',
	'The Shawshank Redemption',
	'The Silence of the Lambs',
	'The Sound of Music',
	'The Third Man',
	'The Treasure of the Sierra Madre',
	'The Wizard of Oz',
	'Titanic',
	'To Kill a Mockingbird',
	'Unforgiven',
	'Vertigo',
	'West Side Story',
	'Wuthering Heights',
];
